version: '3'
services:
  "web-application":
    build: "./webApplication"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./webApplication/src:/webApplication/src"
    depends_on:
      - database
      - redis
  #database:
    #build: ./database
    #ports:
    #- "3306:3306"
    #environment:
      #- MYSQL_ROOT_PASSWORD=user
      #- MYSQL_DATABASE=database
  spa:
    build: "./SPA/"
    ports:
      - "3000:80"
    volumes:
      - "./SPA/src/:/usr/local/apache2/htdocs/"
  database:
    build: ./databaseORM
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: user
      POSTGRES_DB: databaseORM
  redis:
    build: "./session_db"
    volumes:
      - "./session_db"
    environment:
      - REDIS_PASSWORD=user
      # The code below makes it so that someone can't remove all of the files. Check with teacher if it's important:
      # - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
  